name: env
channels:
  - conda-forge
dependencies:
  - netCDF4
  - numpy
  - scipy
  - pandas
  - matplotlib
  - mayavi==4.7.2
  - xarray
  - gridded
  - cmcrameri 
  - rasterio
  - earthengine-api
  - oauth2client
  - google-cloud-logging
  - google-api-python-client
  - google-cloud-storage




name: env
channels:
  - conda-forge
dependencies:
  - affine
  - attrs
  - cftime
  - geojson
  - netCDF4
  - numpy
  - pyparsing
  - pyugrid
  - scipy
  - pandas
  - Shapely
  - matplotlib
  - libgdal
  - gdal
  - Pillow
  - python==3.7
  - pip
  - pip:
    - earthengine-api
    # 3 not compatible with earthengine-api service account
    - oauth2client<4
    - google-cloud-logging
    - google-api-python-client
    # some disconnection issue,  try again with 1.28
    - google-cloud-storage==1.26.0
    - rasterio
    - datetime
    - tqdm
    - mayavi==4.6.2
