name: env
channels:
  - conda-forge
dependencies:
  - netCDF4
  - numpy
  - scipy
  - pandas
  - matplotlib
  - mayavi==4.7.2
  - xarray
  - gridded
  - cmcrameri 
  - rasterio
  - earthengine-api
  - oauth2client
  - google-cloud-logging
  - google-api-python-client
  - google-cloud-storage
