apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: glossis-
spec:
  entrypoint: complete-workflow
  volumes:
  - name: dgds-storage-cleanup
    persistentVolumeClaim:
      claimName: dgds2
  - name: dgds-storage-waterlevel
    persistentVolumeClaim:
      claimName: dgds-waterlevel
  - name: dgds-storage-currents
    persistentVolumeClaim:
      claimName: dgds-currents
  - name: dgds-storage-wind
    persistentVolumeClaim:
      claimName: dgds-wind
  - name: dgds-storage-waves
    persistentVolumeClaim:
      claimName: dgds-waves
  - name: dgds-storage-flowmap
    persistentVolumeClaim:
      claimName: dgds-flowmap
  - name: google-cred
    secret:
      secretName: serviceaccount

  templates:
  - name: complete-workflow
    dag:
      tasks:
      - name: cleanup
        template: glossis
        # Argo arguments
        arguments:
          # Argo parameters
          parameters:
          # input argument for python script
          - name: argument
            value: cleanup
          - name: volume
            value: dgds-storage-cleanup
      - name: waterlevel
        dependencies: [cleanup]
        template: glossis
        arguments:
          parameters:
          - name: argument
            value: waterlevel
          - name: volume
            value: dgds-storage-waterlevel
      - name: currents
        dependencies: [cleanup]
        template: glossis
        arguments:
          parameters:
          - name: argument
            value: currents
          - name: volume
            value: dgds-storage-currents
      - name: wind
        dependencies: [cleanup]
        template: glossis
        arguments:
          parameters:
          - name: argument
            value: wind
          - name: volume
            value: dgds-storage-wind
      - name: waves
        dependencies: [cleanup]
        template: glossis
        arguments:
          parameters:
          - name: argument
            value: waves
          - name: volume
            value: dgds-storage-waves
      - name: flowmap-tiffs
        dependencies: [currents]
        template: glossis
        arguments:
          parameters:
          - name: argument
            value: flowmap-tiffs
          - name: volume
            value: dgds-storage-flowmap
      - name: flowmap-tiles
        dependencies: [flowmap-tiffs]
        template: glossis
        arguments:
          parameters:
          - name: argument
            value: flowmap-tiles
          - name: volume
            value: dgds-storage-flowmap

  - name: glossis
    inputs:
      parameters:
      - name: argument
      - name: volume
    container:
      imagePullPolicy: Always
      image: deltares/dgds-glossis:test
      command: ["python"]
      args: ["/root/glossis.py", "dgds-data", "fews_glossis/", "projects/dgds-gee/glossis", "gee", "--{{inputs.parameters.argument}}"]
      volumeMounts:
      - name: google-cred
        mountPath: "/root/creds"
        readOnly: true
      - name: "{{inputs.parameters.volume}}"
        mountPath: "/root/tmp/netcdfs/"
      resources:
          requests:
            memory: "10G"
      env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: "/root/creds/google_credentials.json"
