apiVersion: v1
kind: Pod
metadata:
  name: dgds
spec:
  volumes:
  - name: google-cred
    secret:
      secretName: serviceaccount
  containers:
  - name: dgds
    image: deltares/dgds-glossis
    # resources:
    #   requests:
    #     memory: "4G"
    command: ["python"]
    args: ["/root/glossis.py", "dgds-data", "fews_glossis/", "projects/dgds-gee/glossis"]
    volumeMounts:
      - name: google-cred
        mountPath: "/root/creds"
        readOnly: true
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: "/root/creds/google_credentials.json"
    imagePullPolicy: Always
