---
# Global configuration
- name: apply common configuration to all nodes
  hosts: localhost
  gather_facts: no

  roles:
   - { role: google_cloud }

- name: apply common configuration to all nodes
  hosts: develop
  gather_facts: no

  roles:
   - { role: common_flask }
   - { role: nginx }
   - { role: uwsgi }
   - { role: frontend }

- name: Configure fews forcasting shell
  hosts: fews
  gather_facts: no

  roles:
    - { role: fews }
